### PR TITLE
Enable grafana

### PR DESCRIPTION
**Pull request by okdas**

### CODE REVIEW

**Review by Olshansk — APPROVED** [review]
Key changes are around line 476:

```yaml

#################################### Users ###############################
[users]
# disable user signup / registration
allow_sign_up = false

# Allow non admin users to create organizations
allow_org_create = false

# Set to true to automatically assign new users to the default organization (id 1)
auto_assign_org = true

# Set this value to automatically add new users to the provided organization (if auto_assign_org above is set to true)
auto_assign_org_id = 1

# Default role new users will be automatically assigned
auto_assign_org_role = Admin
```

**Review by Olshansk — COMMENTED** [review]
Reference can be found here: https://github.com/pokt-network/poktroll/blob/main/localnet/kubernetes/observability-prometheus-stack.yaml#L4

**Review by Olshansk — APPROVED** [review]
Got my 🙈 approval.

Please test it out once it's working!

**Comment by Olshansk** [comment]
@okdas bump

**Comment by okdas** [comment]
@Olshansk I'll have to test after we resolve the current testnet issue. Merging as is now.

**Pull request merged**
